/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Statue({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/bust-lo-draco.glb");

  useFrame(() => (group.current.rotation.y += 0.01));

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0001.geometry}
        material={materials["default"]}
        position={[0, -0.5, 0]}
        scale={[0.2, 0.2, 0.2]}
      />
    </group>
  );
}

useGLTF.preload("/bust-lo-draco.glb");
